name: Tests

on:
  push:
    branches: [main]
  pull_request: {}

jobs:
  test:
    name: Test notebooks
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@85880fa0301c86cca9da44039ee3bb12d3bedbfa # 0.12.1
      - name: Checkout the repository
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # main
      - name: 🐍 Setup uv
        uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86 # v5
      - name: Run tests
        run: |
          uvx --with marimo pytest -v
